# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnY5WAE7CPWO2B3ghQekOqfdlDYiFs-Q
"""



from flask import Flask, request, jsonify
import numpy as np
import tensorflow.lite as tflite

app = Flask(__name__)

# Load the TensorFlow Lite model
interpreter = tflite.Interpreter(model_path="wildfire_model.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json  # Receive data from Arduino (Wokwi)

    # Convert input to NumPy array
    input_data = np.array([data['features']], dtype=np.float32)

    # Perform inference
    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()
    output = interpreter.get_tensor(output_details[0]['index'])

    return jsonify({'prediction': float(output[0])})  # Send prediction back

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

